version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"   # management UI
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn m6_app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - rabbit
  worker:
    build: .
    command: celery -A m6_app worker --loglevel=info
    env_file: .env
    depends_on:
      - rabbit
      - db

volumes:
  postgres_data:

